baseURL = "https://jungu.xyz/"
languageCode = "zh-CN"
title = "ä¸‰åæ–¤é—²ç™½ä¸æ­£æ–‡"
theme = "hugo-theme-diary"
DefaultContentLanguage = "zh"
googleAnalytics = "UA-215766715-2"

[params]
googleSearchCode = "538cd7a0cad502871"

[[menu.main]]
url = "/posts/author/"
name = "ğŸ‘‹ ä½œè€…"
weight = 1

[[menu.main]]
url = "/tags"
name = "ğŸ—‚ï¸ æ ‡ç­¾"
weight = 2

[[menu.main]]
url = "/tags/EN/"
name = "ğŸŒ EN"
weight = 3

[[menu.main]]
url = "/categories"
name = "ğŸ—ƒï¸ åˆ†ç±»"
weight = 4

[[menu.main]]
url = "/posts"
name = "ğŸ—„ï¸ å½’æ¡£"
weight = 5

[[menu.main]]
url = "/index.xml"
name = "â¤ï¸ RSS"
weight = 6

[[menu.main]]
url = "https://mlops.org.cn"
name = "ğŸ”— MLOps ç¤¾åŒº"
weight = 7


